services:
  frostscan:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: frostscan
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      PYTHONUNBUFFERED: "1"
